import type { IconType } from "react-icons";
import {
  SiGo,
  SiPython,
  SiPostgresql,
  SiRedis,
  SiDocker,
  SiNginx,
  SiCloudflare,
  SiGithubactions,
  SiFastapi,
  SiNextdotjs,
  SiTailwindcss,
  SiTypescript,
  SiJavascript,
  SiNodedotjs,
  SiExpress,
  SiFigma,
  SiReact,
} from "react-icons/si";

export const skillIconMap: Record<string, IconType> = {
  SiGo,
  SiPython,
  SiPostgresql,
  SiRedis,
  SiDocker,
  SiNginx,
  SiCloudflare,
  SiGithubactions,
  SiFastapi,
  SiNextdotjs,
  SiTailwindcss,
  SiTypescript,
  SiJavascript,
  SiNodedotjs,
  SiExpress,
  SiFigma,
  SiReact,
};
